# NQ_AI ViT-Base Hybrid Model Configuration
# 87M parameter Google ViT-Base-Patch16-224 with numerical features

# Data Configuration
data:
  source: "stooq"
  ticker: "NQ.F"  # Stooq NQ futures symbol
  timeframe: "daily"
  bars_per_chart: 30  # 30 daily bars per chart (6 weeks context)
  start_year: 2000
  end_year: 2025
  
# Chart Generation
chart:
  width: 12
  height: 8
  dpi: 100
  style: "yahoo"
  prev_high_color: "green"
  prev_low_color: "red"
  line_width: 2
  volume: false
  title: true
  
# Pattern Classification (4-class system)
classification:
  num_classes: 4
  labels:
    1: "High Breakout"      # Daily high >= previous day high only
    2: "Low Breakdown"      # Daily low <= previous day low only  
    3: "Range Expansion"    # Both levels touched
    4: "Range Bound"        # Neither level touched
    
# Numerical Features (Disabled for Pure Visual Mode)
features:
  numerical_features: 0
  feature_names: []
    
# ViT-Base Model Configuration (RunPod Optimized)
model:
  # ViT-Base Architecture (Google)
  name: "vit_base_patch16_224"
  image_size: 224
  patch_size: 16
  hidden_size: 768          # ViT-Base hidden dimension
  num_layers: 12            # ViT-Base transformer layers
  num_heads: 12             # ViT-Base attention heads
  mlp_dim: 3072             # ViT-Base MLP dimension
  dropout_rate: 0.1
  
  # RunPod Training parameters (No Early Stopping)
  batch_size: 8             # Optimal batch size for pure visual
  learning_rate: 0.0001     # Constant LR, no scheduling
  epochs: 30                # Fixed 30 epochs, no early stopping
  weight_decay: 0.01
  
  # Pure Visual Mode (No Feature Fusion)
  visual_only: true         # Disable numerical features
  use_feature_fusion: false # Pure ViT-Base visual learning
    
# Training Configuration (RunPod No-Stop Mode)
training:
  train_split: 0.8
  use_class_weights: true
  data_augmentation: false  # Charts should not be augmented
  
  # RunPod Optimizations
  mixed_precision: false    # Disabled for float64 training
  gradient_clipping: true   # Stabilize training on cloud GPU
  checkpoint_frequency: 5   # Save every 5 epochs for RunPod
  
  # No Early Stopping - Complete 30 Epochs
  early_stopping: false    # DISABLED for pure visual training
  lr_scheduling: false     # DISABLED - constant learning rate
  
# File Paths
paths:
  data_root: "data"
  images: "data/images"
  labels: "data/labels"
  metadata: "data/metadata"
  models: "models"
  outputs: "models/outputs"
  checkpoints: "models/outputs/checkpoints"
  logs_dir: "logs"
  tensorboard_logs: "models/outputs/logs"
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# System Information
system:
  name: "NQ_AI ViT-Base Hybrid Model"
  version: "1.0"
  description: "ViT-Base-Patch16-224 (87M params) with numerical features for daily NQ pattern analysis"
  architecture: "Google ViT-Base + Feature Fusion"
  parameters: "87M (ViT-Base) + additional fusion layers"
  data_period: "25 years (2000-2025)"
  expected_samples: 6235